export let locale = 'ru';
const strings = {
  ru: {
    title:'Поймай слово.<br><em>Найди его пару.</em>',story:'Помоги опоссуму BOZUU донести звёздочку до маяка.<br>50 остановок. Новые слова зажигают путь.',choose:'Выбери остановку',themes:'50 тем',search:'Найти тему: еда, космос, семья…',empty:'Такой темы пока нет. Попробуй другое слово.',play:'Начать полёт →',home:'← Темы',restart:'Заново ↻',closer:'На 10 пар ближе.',other:'Выбрать другую тему',headphones:'🎧 Лучше со звуком',footer:'Сделай вдох. Ты уже учишься.',motion:'Анимация',sound:'Звук',pairs:'пар',pairCount:'{n} пар',round:'10 пар за раунд',journeyStart:'Путешествие начинается',journeyNear:'Маяк становится ближе',journeyEnd:'BOZUU добрался до маяка! ✦',lights:'{n} из 50 огоньков зажжено',rhythm:'✧ Лови свой ритм',streak:'✦ {n} подряд',cheer:'Уиии! Так держать!',cheerBig:'Уиии! Вот это полёт!',three:'✨ Три подряд! Поймал ритм.',five:'🌈 Пять подряд! Quel talent !',ten:'🏅 Идеальный полёт!',muted:'Звук выключен — включи ♪ вверху экрана.',audioMissing:'Аудио недоступно. Попробуй нажать на слово ещё раз.',storage:'Хранилище браузера недоступно: прогресс только до закрытия страницы.',lifetime:'Уже найдено пар: {n}. Petit à petit !',smallStep:'Твой маленький шаг к большому bonjour.',best:'Лучшая серия: {n}.',listen:'французский, прослушать',english:'английский',pickFrench:'Теперь найди французское слово.',pickEnglish:'Теперь найди английский перевод.',tryAgain:'Почти! Попробуй другую пару.',startHint:'Выбери французское слово — и послушай его.',endStory:'Все 50 огоньков сияют. BOZUU донёс звёздочку до маяка!',newLight:'Новый огонёк на пути к маяку!',oldLight:'Знакомая остановка стала ещё ближе.',route:'Пройдено {n} из 50.',next:'К следующей остановке →',again:'Ещё один полёт →',review:'Отличная практика. Эти слова ещё встретим — нажми, чтобы послушать:',perfect:'Все пары найдены без ошибок. Magnifique !',rewardPerfect:'🏅 Безупречный полёт',rewardFive:'🌈 Ветер в парусах',reward:'☀ Ещё один шаг вперёд',stats:'10 пар найдено · лучшая серия {best} · всего пар {total}',mascot:'Опоссум BOZUU со звёздочкой',lighthouse:'Маяк',completed:'Пройденные темы',game:'Найди пары слов',themeLabel:'Темы',language:'Язык интерфейса'
  },
  en: {
    title:'Catch a word.<br><em>Find its match.</em>',story:'Help BOZUU the opossum carry a little star to the lighthouse.<br>50 stops. Every new word lights the way.',choose:'Choose a stop',themes:'50 themes',search:'Find a theme: food, space, family…',empty:'No themes found. Try another word.',play:'Let’s take flight →',home:'← Themes',restart:'Restart ↻',closer:'10 pairs closer.',other:'Choose another theme',headphones:'🎧 Better with sound',footer:'Take a breath. You’re already learning.',motion:'Animation',sound:'Sound',pairs:'pairs',pairCount:'{n} pairs',round:'10 pairs per round',journeyStart:'The journey begins',journeyNear:'The lighthouse is getting closer',journeyEnd:'BOZUU reached the lighthouse! ✦',lights:'{n} of 50 lights are glowing',rhythm:'✧ Find your rhythm',streak:'✦ {n} in a row',cheer:'Wheee! You’ve got this!',cheerBig:'Wheee! What a flight!',three:'✨ Three in a row! Nice rhythm.',five:'🌈 Five in a row! Quel talent !',ten:'🏅 A perfect flight!',muted:'Sound is off — tap ♪ at the top to turn it on.',audioMissing:'Audio unavailable. Try tapping the word again.',storage:'Browser storage is unavailable: progress lasts until you close this page.',lifetime:'Pairs found: {n}. Petit à petit !',smallStep:'A little step toward a big bonjour.',best:'Best streak: {n}.',listen:'French, listen',english:'English',pickFrench:'Now find the French word.',pickEnglish:'Now find its English meaning.',tryAgain:'Almost! Try another pair.',startHint:'Tap a French word to hear it.',endStory:'All 50 lights are shining. BOZUU brought the star to the lighthouse!',newLight:'A new light on the way to the lighthouse!',oldLight:'A familiar stop, a little more practice.',route:'Completed {n} of 50.',next:'To the next stop →',again:'Another flight →',review:'Lovely practice. Let’s revisit these words — tap to listen:',perfect:'Every pair matched without a mistake. Magnifique !',rewardPerfect:'🏅 A flawless flight',rewardFive:'🌈 Wind in your sails',reward:'☀ One more step forward',stats:'10 pairs found · best streak {best} · total pairs {total}',mascot:'BOZUU the opossum holding a star',lighthouse:'Lighthouse',completed:'Completed themes',game:'Match the word pairs',themeLabel:'Themes',language:'Interface language'
  }
};
export function setLocale(value) {locale = value === 'en' ? 'en' : 'ru'; document.documentElement.lang = locale;}
export function t(key,values={}) {return Object.entries(values).reduce((text,[name,value])=>text.replaceAll(`{${name}}`,String(value)),strings[locale][key] || key);}
export function themeName(theme) {
  const names = {basics:'Basics',food:'At the café',city:'City',greetings:'Greetings',family:'Family',body:'Body',face:'Face',clothes:'Clothes',colors:'Colors',numbers:'Numbers',time:'Time',calendar:'Calendar',weather:'Weather',seasons:'Seasons',fruit:'Fruit',vegetables:'Vegetables',drinks:'Drinks',desserts:'Desserts',cooking:'Cooking',kitchen:'Kitchen',home:'Home',furniture:'Furniture',bathroom:'Bathroom',pets:'Pets',wildlife:'Wild animals',farm:'Farm',ocean:'Ocean',insects:'Tiny creatures',landscapes:'Nature',plants:'Plants',transport:'Transport',travel:'Travel',hotel:'Hotel',directions:'Directions',shopping:'Shopping',money:'Money',school:'School',work:'Work',professions:'Professions',technology:'Technology',music:'Music',art:'Art',sports:'Sports',hobbies:'Hobbies',emotions:'Emotions',qualities:'Qualities',actions:'Actions',communication:'Communication',space:'Space',holidays:'Celebrations'};
  return locale === 'en' ? names[theme.id] : theme.title;
}
